app/models.py
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask import url_for
from datetime import datetime


class PaginatedAPIMixin():
    @staticmethod
    def to_collection_dict(query, page, per_page, endpoint, **kwargs):
        resources = query.paginate(page, per_page, False)
        data = {
            'items': [item.to_dict() for item in resources.items],
            '_meta': {
                'page': page,
                'per_page': per_page,
                'total_pages': resources.pages,
                'total_items': resources.total
            },
            '_links': {
                'self': url_for(endpoint, page=page, per_page=per_page,
                                **kwargs),
                'next': url_for(endpoint, page=page + 1, per_page=per_page,
                                **kwargs) if resources.has_next else None,
                'prev': url_for(endpoint, page=page - 1, per_page=per_page,
                                **kwargs) if resources.has_prev else None
            }
        }
        return data


class Users(UserMixin, PaginatedAPIMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(150))
    email = db.Column(db.String(150), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    profile = db.relationship('Profile', backref='specialist', lazy='dynamic')

    def __repr__(self):
        return f"Fullname is - {self.fullname}"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        pass


class Profile(UserMixin, PaginatedAPIMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    city = db.Column(db.String(120), default="Word")
    education = db.Column(db.String(140))
    mastery = db.Column(db.String(120))
    skill = db.Column(db.String(120))
    contact = db.Column(db.String(80))
    birthday = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return f'Profile - {self.city}'


@login.user_loader
def load_user(id):
    return Users.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, SelectField
from wtforms import validators
from wtforms.validators import ValidationError, DataRequired, Length
import re
import datetime


class ProfileForm(FlaskForm):
    """worksheet form with any custom validators"""
    # added any skills for example
    label = [('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text'),
            ('jv', 'Java'), ('ph', 'PHP'), ('ex', 'Excel')]
    city = StringField('Место проживания:', validators=[DataRequired(),
                                                        Length(min=2)])
    education = StringField('Образование', validators=[DataRequired()])
    mastery = StringField('Специализация', validators=[DataRequired()])
    skill = SelectField("Проф. навык", choices=label)

    def detect_age(self, age):
        """age restrictions"""
        res = datetime.datetime.today().year - self.birthday.data.year
        if res < 18:
            raise ValidationError("Ваш возраст меньше 18")

    def validate_number_phone(self, number):
        """Validation correct kz number phone"""
        if not re.search('^\+7\d{10}$', self.contact.data):
            raise ValidationError("Вы ввели не корректный номер")

    birthday = DateField('Datetime', format='%Y-%m-%d', validators=(validators.Optional(),
                                                                    detect_age))
    contact = StringField('Контактные данные', description="номер телефона",
                          validators=[validate_number_phone])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

# initializations
db = SQLAlchemy()
migration = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = ('Please log in to access this page.')
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migration.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as error_bp
    app.register_blueprint(error_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/main/__init__.py
from flask import Blueprint
bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db
from app.main import bp
from flask import request, redirect, url_for, flash, render_template, current_app
from flask_login import current_user, login_required
from app.main.forms import ProfileForm
from app.models import Profile, Users
import app.utils


@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
def index():
    page = request.args.get('page', 1, type=int)
    dossier = Users.query.order_by(Users.email.desc()).paginate(
        page, current_app.config['DOSSIER_PER_PAGE'], False)
    next_url = url_for('main.index', page=dossier.next_num) \
        if dossier.has_next else None
    prev_url = url_for('main.index', page=dossier.prev_num) \
        if dossier.has_prev else None
    return render_template('index.html', title='Home', posts=dossier.items,
                           next_url=next_url, prev_url=prev_url)

# profile editing
@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    data = Profile.query.filter_by(user_id=id).first_or_404()
    age = app.utils.get_age(data.birthday)
    form = ProfileForm()
    if form.validate_on_submit():
        data.city = form.city.data
        data.education = form.education.data
        data.mastery = form.mastery.data
        data.skill = form.skill.data
        data.birthday = form.birthday.data
        data.contact = form.contact.data
        db.session.commit()
        flash('Ваши данные отредактированы')
        return render_template('view.html', user=data, form=form, age=age)
    return render_template('edit_profile.html', user=user, form=form, data=data, id=id)


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    check_exist = Profile.query.filter_by(user_id=current_user.id).first()
    # if profile is completed redirect on edit profile
    if check_exist:
        return redirect(url_for('main.edit', id=current_user.id))
    form = ProfileForm()
    if form.validate_on_submit():
        profile = Profile(
            city=form.city.data,
            education=form.education.data,
            mastery=form.mastery.data,
            skill=form.skill.data,
            birthday=form.birthday.data,
            contact=form.contact.data,
            specialist=current_user)
        db.session.add(profile)
        db.session.commit()
        flash('Анкета успешно заполнена')
        return redirect(url_for('main.index'))
    return render_template('profile.html', form=form)


# view for all users
@bp.route('/user/<id>', methods=['GET'])
def user(id):
    data = Profile.query.filter_by(user_id=id).first_or_404()
    age = app.utils.get_age(data.birthday)
    return render_template('view.html', user=data, age=age)

app/templates/_post.html
    <table class="table table-hover">
        <tr>
            <td>
                {% set user_link %}
                    <a href="{{ url_for('main.user', id=post.id) }}">
                        {{ post.fullname }}</a>
                {% endset %}
                <p>{{ user_link }}</p>
                <br>
            </td>
        </tr>
    </table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Rating{% else %}{{('Welcome to Microblog') }}{% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{ ('Home') }}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ 'Login' }}</a></li>
                    <li><a href="{{ url_for('auth.register') }}">{{ 'Register' }}</a></li>
                    {% else %}
                    <li><a href="{{ url_for('main.profile', id=current_user.id) }}">{{ 'Профиль' }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ 'Logout' }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>

    {% block footer %}
        <div class="footer">
            <footer class="text-center text-lg-start text-white" style="background-color: #929fba">
                <div style="padding: 10px">
                  <!-- Copyright -->
                  <div class="footer-copysright text-center text-white">© 2022 Copyright:
                    <a href="https://www.instagram.com/arman_nu_95" target="_blank">Instagram</a>
                  </div>
                  <!-- Copyright -->
                </div>
            </footer>
        </div>
    {% endblock %}
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}


<h1>{{ 'Редактор профиля' }}</h1>
<em>{{current_user.fullname}}</em>
<br/>
{% if id == current_user.id %}

	<br/>
	<div class="shadow p-3 mb-5 bg-body rounded">
	<form action="/edit/{{ data.specialist.id }}" method="POST">
		{{ form.hidden_tag() }}

		{{ form.city.label(class="form-label") }}

		{{ form.city(class="form-control", value=data.city) }}
		<br/>

		{{ form.education.label(class="form-label") }}

		{{ form.education(class="form-control", value=data.education) }}
		<br/>

		{{ form.mastery.label(class="form-label") }}

		{{ form.mastery(class="form-control", value=data.mastery) }}
		<br/>

		{{ form.skill.label(class="form-label") }}

		{{ form.skill(class="form-control", value=data.skill) }}
        <br/>

		{{ form.birthday.label(class="form-label") }}

		{{ form.birthday(class="form-control", value=data.birthday.date()) }}
        <br/>

		{{ form.contact.label(class="form-label") }}

		{{ form.contact(class="form-control", value=data.contact) }}

		<br/>

		{{ form.submit(class="btn btn-secondary") }}

	</form>
</div>
<br/><br/><br/>

{% else %}
 <div class="alert alert-warning alert-dismissible fade show" role="alert">
	  Sorry! You Can't Edit This User...
	  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>

	<h2>Access Denied!</h2>
	<p>Sorry, you cannot access this user profile...</p>

{% endif %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
     {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}


    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer posts' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Older posts' }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<h1>Анкетные данные</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
<br>

{% endblock %}

app/templates/userv.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <table class="table table-hover">
        <tr>
            <td>
                <h3>{{ user.specialist.fullname }}</h3>
                <em>Дата рождения {{ user.birthday.date() }}, {{age}} - лет</em>
                <br>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Место проживание</h4>
            </td>
            <td>
                <span >{{ user.city }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Образование</h4>
            </td>
            <td>
                <span >{{ user.education }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Специализация</h4>
            </td>
            <td>
                <span >{{ user.mastery }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Проффесиональные навыки</h4>
            </td>
            <td>
                <span >{{ user.skill }}</span>
            </td>
        </tr>
    </table>
{% endblock %}

app/templates/view.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <table class="table table-hover">
        <tr>
            <td>
                <h3>{{ user.specialist.fullname }}</h3>
                <em>Дата рождения {{ user.birthday.date() }}, {{age}} - лет</em>
                <br>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Место проживание</h4>
            </td>
            <td>
                <span >{{ user.city }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Образование</h4>
            </td>
            <td>
                <span >{{ user.education }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Специализация</h4>
            </td>
            <td>
                <span >{{ user.mastery }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Проффесиональные навыки</h4>
            </td>
            <td>
                <span >{{ user.skill }}</span>
            </td>
        </tr>
                <tr>
            <td>
                <h4>Контактные данные</h4>
            </td>
            <td>
                <span >{{ user.contact }}</span>
            </td>
        </tr>
    </table>
{% endblock %}